import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const kernel = readFileSync(new URL('../src/kernel.js', import.meta.url), 'utf8');
const server = readFileSync(new URL('../src/server.js', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/dashboard-runtime.js', import.meta.url), 'utf8');
const renderer = readFileSync(new URL('../src/neural-field-renderer.js', import.meta.url), 'utf8');
const db = readFileSync(new URL('../src/db.js', import.meta.url), 'utf8');

test('live neural events are generated by kernel transitions and exposed read-only', () => {
  for (const token of [
    'emitNeuralSignal({',
    'neuralSignalsSince(since = 0',
    "kind: 'reflection'",
    "kind: 'intention'",
    "kind: 'learning'",
    "kind: ok ? 'outcome-success' : 'outcome-failure'",
  ]) assert.ok(kernel.includes(token), token);
  assert.ok(server.includes("app.get('/api/kernel/public/neural-signals'"));
});

test('dashboard polls live neural events independently from 8-second topology refresh', () => {
  assert.ok(dashboard.includes("api('/api/kernel/public/neural-signals?since='"));
  assert.ok(dashboard.includes('setInterval(refreshNeuralSignals,1000)'));
  assert.ok(dashboard.includes('setInterval(refresh,8000)'));
  assert.ok(renderer.includes('function ingestSignals(events)'));
  assert.ok(renderer.includes('function drawLiveSignalsV8(t)'));
  assert.ok(renderer.includes('drawLiveSignalsV8(t)'));
});

test('continuity retrieval keeps operational history separate from relationship filtering', () => {
  assert.ok(kernel.includes('async continuitySnapshot(queryText ='));
  assert.ok(kernel.includes('operational_messages'));
  assert.ok(kernel.includes("plan.context_scope !== 'relationship'"));
  assert.ok(kernel.includes('this.continuitySnapshot(content)'));
});

test('logical backups include conversation and operational continuity records', () => {
  for (const token of [
    'aura_cloud_messages',
    'aura_cognitive_traces',
    'aura_outcomes',
    'aura_organism_events',
    'messages,',
    'cognitive_traces: cognitiveTraces',
    'organism_events: organismEvents',
  ]) assert.ok(db.includes(token), token);
});
