export const CORE_QUANTIC_PRODUCTS = Object.freeze([
  {
    id: 'aura',
    name: 'AURA',
    repository: 'XDSawyerLoL/Auralive',
    objective: 'Intelligence mère et couche de direction de Quantic Sillage : identité, mémoire, raisonnement, curiosité, orchestration, évolution et gouvernance opérationnelle.',
    criticality: 1,
    role: 'platform-core',
    parent: null,
    specialization: 'intelligence-and-control-plane',
    capabilities: ['reasoning','memory','curiosity','research','orchestration','evolution','mesh','fabric','governance'],
    aura_bridge: 'native',
  },
  {
    id: 'quantic-studio',
    name: 'Quantic Studio',
    repository: 'XDSawyerLoL/Auralive',
    objective: 'Logiciel de streaming vivant de Quantic Sillage : diffusion, scènes, audio, overlays, avatar, communauté et automatisations live.',
    criticality: 0.84,
    role: 'product',
    parent: 'aura',
    specialization: 'live-streaming',
    capabilities: ['streaming','broadcast','scenes','audio','overlays','live-avatar','community','live-automation'],
    aura_bridge: 'required',
  },
  {
    id: 'quantic-glide',
    name: 'Quantic Glide',
    repository: 'XDSawyerLoL/Quantic-Browser',
    objective: 'Navigateur Quantic pilotable par AURA et interface de perception/navigation Web pour l’utilisateur.',
    criticality: 0.92,
    role: 'product',
    parent: 'aura',
    specialization: 'web-browser',
    capabilities: ['browser','web-context','tabs','research-context','downloads'],
    aura_bridge: 'native',
  },
  {
    id: 'quantic-os',
    name: 'Quantic OS',
    repository: 'XDSawyerLoL/QUANTIC-OS',
    objective: 'Couche système et environnement agentique local de Quantic.',
    criticality: 0.94,
    role: 'product',
    parent: 'aura',
    specialization: 'operating-system',
    capabilities: ['system','local-control','agents','sandbox','desktop'],
    aura_bridge: 'required',
  },
  {
    id: 'quantic-mail',
    name: 'Quantic Mail',
    repository: 'XDSawyerLoL/QuanticMail',
    objective: 'Communication privée, réseau Quantic et messagerie chiffrée.',
    criticality: 0.9,
    role: 'product',
    parent: 'aura',
    specialization: 'mail-and-private-messaging',
    capabilities: ['mail','private-messaging','identity','devices','relay'],
    aura_bridge: 'required',
  },
  {
    id: 'identity-vault',
    name: 'Identity Vault',
    repository: 'XDSawyerLoL/QuanticMail',
    objective: 'Coffre d’identité Quantic : identité persistante, récupération chiffrée, portabilité et autorisation locale.',
    criticality: 0.93,
    role: 'product',
    parent: 'aura',
    specialization: 'identity-and-credentials-vault',
    capabilities: ['identity','vault','recovery','portable-identity','device-trust','encryption'],
    aura_bridge: 'required',
  },
  {
    id: 'zoon',
    name: 'ZOON',
    repository: 'XDSawyerLoL/QuanticSillage',
    objective: 'Couche sociale Quantic : publications, interactions, médias et flux.',
    criticality: 0.82,
    role: 'product',
    parent: 'aura',
    specialization: 'social-network',
    capabilities: ['social','feed','publishing','media','community'],
    aura_bridge: 'required',
  },
  {
    id: 'pulse',
    name: 'Quantic Pulse',
    repository: 'XDSawyerLoL/QuanticSillage',
    objective: 'Couche sociale historique/compatibilité et flux conversationnels Quantic.',
    criticality: 0.7,
    role: 'product',
    parent: 'aura',
    specialization: 'social-compatibility-layer',
    capabilities: ['social','feed','secure-session'],
    aura_bridge: 'required',
  },
  {
    id: 'quantic-news',
    name: 'Quantic News',
    repository: 'XDSawyerLoL/QuanticSillage',
    objective: 'Veille informationnelle et production de flux d’actualité Quantic.',
    criticality: 0.78,
    role: 'product',
    parent: 'aura',
    specialization: 'news-and-information',
    capabilities: ['news','rss','monitoring','publishing','sources'],
    aura_bridge: 'required',
  },
  {
    id: 'providence',
    name: 'Providence',
    repository: 'XDSawyerLoL/Human-Agency-Engine',
    objective: 'Analyse profonde, signaux, scénarios, risques et aide à la décision.',
    criticality: 0.88,
    role: 'product',
    parent: 'aura',
    specialization: 'analysis-and-decision-support',
    capabilities: ['analysis','signals','risk','scenarios','evidence'],
    aura_bridge: 'required',
  },
  {
    id: 'horizon',
    name: 'HORIZON',
    repository: 'XDSawyerLoL/Human-Agency-Engine',
    objective: 'Perception du monde, signaux externes et chaînes d’impact pour AURA.',
    criticality: 0.86,
    role: 'product',
    parent: 'aura',
    specialization: 'world-perception-and-forecast-context',
    capabilities: ['world-signals','weather','impact-chain','forecast-context'],
    aura_bridge: 'native',
  },
]);

export async function seedQuanticProducts(commandCenter) {
  const results = [];
  for (const product of CORE_QUANTIC_PRODUCTS) {
    const existing = (await commandCenter.services()).find((row) => row.id === product.id);
    const state = existing?.state || (product.id === 'aura' ? 'online' : 'unknown');
    const stateDetail = existing?.state_detail
      || (product.id === 'aura'
        ? 'Noyau AURA actif.'
        : product.aura_bridge === 'native'
          ? 'Pont AURA natif déclaré; observation runtime attendue.'
          : 'Pont AURA universel requis; observation runtime attendue.');
    results.push(await commandCenter.upsertService({
      id: product.id,
      name: product.name,
      kind: product.role === 'platform-core' ? 'platform-core' : 'quantic-product',
      objective: product.objective,
      repository: product.repository,
      criticality: product.criticality,
      enabled: true,
      state,
      state_detail: stateDetail,
      last_observed_at: existing?.last_observed_at || '',
      metadata: {
        ...(existing?.metadata || {}),
        capabilities: product.capabilities,
        aura_bridge: product.aura_bridge,
        role: product.role || 'product',
        parent: Object.prototype.hasOwnProperty.call(product, 'parent') ? product.parent : 'aura',
        specialization: product.specialization || '',
        writable_by_aura: true,
        modification_policy: 'branch-test-canary-promote',
        ecosystem: 'quantic-sillage',
        product_identity_required: product.id !== 'aura',
        allowed_bridge_scopes: product.id === 'aura'
          ? []
          : ['product:register-self','product:observe','product:event'],
      },
    }));
  }
  return results;
}
